### ISSUE TITLE
How to specify path to a Lua interpreter?

### ISSUE THREAD

**Issue by ligurio** [Primordus/lua-quickcheck#25]
I want to use lqc with specific version of Lua interpreter, but I don't understand how to do it.
Shebang in `bin/lqc` prompt that always used `lua` interpeter found in $PATH:
```lua
#!/usr/bin/env lua

local app = require 'lqc.cli.app'
app.main(arg)
```
How to use specify path to another Lua interpreter without patching `lqc` source code?
Please advice.

**Comment by luc-tielen** [comment]
It's been a while since I used Lua/this library, but in the CI I test my library against various Lua versions (5.1, 5.2, LuaJIT, ...).
The shebang uses `/usr/bin/env` instead of lua directly, which makes it possible to use different Lua versions.

If I remember correctly, your `luarocks` package manager is linked to your lua version. So if you have Lua 5.2 for example, it will install `lqc` for 5.2 (see installation instructions in README how to install this library).

Hope this helps. :smile:

**Comment by ligurio** [comment]
@luc-tielen Yeah, looks like it is possible to set any interpreter via env variable LUA.
BTW is it possible to use library without cli runner?

**Comment by luc-tielen** [comment]
Yes that's possible, in the end the CLI calls [this lua file](https://github.com/luc-tielen/lua-quickcheck/blob/master/lqc/cli/app.lua), which should be installed via luarocks as well.
If you manage to call `app.main` from your own Lua code you are all set.

**Comment by ligurio** [comment]
Thanks!
